script:
  - exit 0

notifications:
  webhooks:
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/
    on_pull_requests: false
    on_success: always
    on_failure: never
    on_start: never
    on_cancel: never
    on_error: never